### ISSUE TITLE
DESPITE me putting my .env file into the list of gitIgnore, it claims there is two tokens

### ISSUE THREAD

**Issue by djlptts** [speckly/sucorn#10]
For the life of me I cannot keep track of where the frick I have to put the token.

**Comment by djlptts** [comment]
After Reinstalling it, it claims it wants to expose the secret in order to continue
![Screenshot 2024-04-01 at 12 29 01](https://github.com/speckly/sucorn/assets/125202938/0f05a64b-d7b6-4097-8ed9-3de6750636ac)

**Comment by speckly** [comment]
please ONLY open issues related to issues with this repo, i dont know how many times i have to say this
