### ISSUE TITLE
Current project root directory

### ISSUE THREAD

**Issue by djlptts** [speckly/sucorn#5]
![Screenshot 2024-03-18 at 12 37 48](https://github.com/speckly/sucorn/assets/125202938/da4cb5b5-fbd6-4a03-aa9d-1f0ad8ebdd89)

**Comment by djlptts** [comment]
![Screenshot 2024-03-18 at 12 39 27](https://github.com/speckly/sucorn/assets/125202938/789c51f1-75fc-484d-b446-ca968433ef32)

**Comment by speckly** [comment]
related to #4 , please just add comments
