### ISSUE TITLE
New Issues arose in Suclone's aclient.py

### ISSUE THREAD

**Issue by djlptts** [speckly/sucorn#7]
![Screenshot 2024-03-18 at 13 05 25](https://github.com/speckly/sucorn/assets/125202938/848511c6-322d-4c6f-b207-9176809bfcc2)
![Screenshot 2024-03-18 at 13 05 37](https://github.com/speckly/sucorn/assets/125202938/cde1ee9c-05eb-44ab-b167-8e4d791fac3b)

**Comment by speckly** [comment]
[skill issue](https://www.freecodecamp.org/news/module-not-found-error-in-python-solved/)
